### PR TITLE
Create balancing parenthesis.cpp

### PR DESCRIPTION
**Pull request by KhushiRana2003**

### CODE REVIEW

**Comment by KhushiRana2003** [comment]
Have to accepted my pull request??

**Comment by KhushiRana2003** [comment]
Have to accepted my pull request??

**Comment by KhushiRana2003** [comment]
Hii..
But this is not showing in hacktoberfest official site.
THere are only 3 in progress.. this repo is not there. 
Why??

**Comment by abhaygupta12** [comment]
Yes khushi
 l am very sorry to say that my repo no more in count of Hactoberfest.
So sorry ones again.

**Pull request merged**
